#!/bin/bash
# Script that will make clean until I have a makefile

rm *.o
rm -rf service_layer
rm -rf backend_store
protoc -I ../protos --cpp_out=. ../protos/backendStore.proto

g++ -std=c++11 `pkg-config --cflags protobuf grpc` -g -c -o backendStore.pb.o backendStore.pb.cc

protoc -I ../protos --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` ../protos/backendStore.proto

g++ -std=c++11 `pkg-config --cflags protobuf grpc` -g -c -o backendStore.grpc.pb.o backendStore.grpc.pb.cc

g++ -std=c++11 `pkg-config --cflags protobuf grpc` -g -c -o key_value_store_service_impl.o key_value_store_service_impl.cc

g++ -std=c++11 `pkg-config --cflags protobuf grpc` -g -c -o key_value_client_interface.o key_value_client_interface.cc

g++ -std=c++11 `pkg-config --cflags protobuf grpc` -g -c -o key_value_client.o key_value_client.cc

g++ -std=c++11 `pkg-config --cflags protobuf grpc` -g -c -o key_value_store.o key_value_store.cc

g++ -std=c++11 `pkg-config --cflags protobuf grpc`  -g -c -o backend_store.o backend_store.cc

g++ backendStore.pb.o backendStore.grpc.pb.o backend_store.o key_value_store_service_impl.o key_value_store.o key_value_client_interface.o key_value_client.o -g -L/usr/local/lib `pkg-config --libs protobuf grpc++ grpc` -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -ldl -o backend_store

protoc -I ../protos --cpp_out=. ../protos/service.proto

g++ -std=c++11 `pkg-config --cflags protobuf grpc` -c -o service.pb.o service.pb.cc

protoc -I ../protos --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` ../protos/service.proto

g++ -std=c++11 `pkg-config --cflags protobuf grpc` -g -c -o key_value_client.o key_value_client.cc

g++ -std=c++11 `pkg-config --cflags protobuf grpc` -g -c -o key_value_client_interface.o key_value_client_interface.cc

g++ -std=c++11 `pkg-config --cflags protobuf grpc` -g -c -o service.grpc.pb.o service.grpc.pb.cc

g++ -std=c++11 `pkg-config --cflags protobuf grpc` -g -c -o service.o service.cc

g++ -std=c++11 `pkg-config --cflags protobuf grpc` -g -c -o service_layer_service_impl.o service_layer_service_impl.cc

g++ -std=c++11 `pkg-config --cflags protobuf grpc`  -g -c -o service_layer.o service_layer.cc

g++ backendStore.pb.o backendStore.grpc.pb.o service.pb.o service.grpc.pb.o service_layer.o key_value_client.o service_layer_service_impl.o service.o key_value_client_interface.o -g -L/usr/local/lib `pkg-config --libs protobuf grpc++ grpc` -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -ldl -o service_layer
